version: '2'
services:
  web:
    container_name: squiddlebit
    restart: always
    build:
        context: .
    ports:
      - "8081:8081"
    networks:
      - default
      - backend
    environment:
      YAMIGO_ENVIRONMENT: production
    volumes:
      - ./:/app
networks:
    backend:
      external: true